{% set name = "openfermionpyscf" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openfermionpyscf-{{ version }}.tar.gz
  sha256: 60b7a8a03e4e2415b5e5b4f8aed02203add0fe90eafff5873580cf2d6d67729f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - openfermion >=0.5
    - pyscf
    - pytest
    - python >={{ python_min }}

test:
  imports:
    - openfermionpyscf
  commands:
    - pip check
    - pytest openfermionpyscf/tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - openfermionpyscf/tests

about:
  home: http://www.openfermion.org
  summary: A plugin allowing OpenFermion to interface with PySCF.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  dev_url: https://github.com/quantumlib/OpenFermion-PySCF

extra:
  recipe-maintainers:
    - BastianZim
